name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-snapshot:
    runs-on: macos-14
    if: github.event.repository.fork == false
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Check
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: check
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

      - name: Publish Snapshots
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
